service: lambda-orchestrator
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
        - lex:*
      Resource: "*"

functions:
  Orchestrator:
    handler: friday_orchestrator.handler.orchestrator
    events:
      - httpApi:
          path: /orchestrator
          method: post

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
     dockerizePip: true

package:
  exclude:
    - ./**
  include:
    - friday_orchestrator/**